language: python
python:
  - "3.8"

env:
  global:
    MOZ_HEADLESS=1

addons:
  firefox: latest
  apt:
    packages:
      [firefox-geckodriver]

jobs:
  include:
    - stage: test
      script: pip install -r requirements-dev.txt && make test
    - stage: deploy
      script: . scripts/add_rsa_key.sh
      deploy:
        provider: script
        skip_cleanup: true
        script: bash scripts/deploy.sh
        on:
          branch: main
    - stage: "Test staging site"
      script: python scripts/wait_for_ok.py && . scripts/test_against_staging.sh