language: python
python:
  - "3.8"

env:
  global:
    MOZ_HEADLESS=1

addons:
  firefox: latest
  apt:
    packages:
      [firefox-geckodriver]

install:
  pip install -r requirements.txt
  pip install -r requirements-dev.txt
  pip install codecov

script:
  make test

after_success:
  - codecov