language: python
python:
  - "3.8"

services:
  - docker

env:
  global:
    MOZ_HEADLESS=1

addons:
  firefox: latest
  apt:
    packages:
      [firefox-geckodriver]

install:
  - docker build -t jmeans319/531 .

script:
  - docker run jmeans319/531 make test

after_success:
  - codecov
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jmeans319/531