language: python
python:
  - "3.8"

services:
  - docker


install:
  - docker build -t jmeans319/531 .

script:
  - docker run jmeans319/531 make test

before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in .traivs/deploy_rsa.enc -out .travis/deploy_rsa -d
  - eval "$(ssh_agent -s)"
  - cp .travis/deploy_rsa ~/.ssh/deploy_rsa
  - chmod 600 ~/.ssh/deploy_rsa
  - ssh-add ~/.ssh/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: main

after_success:
  - codecov
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jmeans319/531