version: '3.8'

services:
  web:
    build: .
    command: gunicorn lifting.wsgi:application --bind 0.0.0.0:8080
    volumes:
    - static_volume:/home/sites/www.imtoodumbtofigureout531onmyown-staging.com/static
    ports:
      - 8000:8080
    env_file:
      - ./.env

#   nginx:
#     build: ./nginx
#     volumes:
#       - static_volume:/home/sites/www.imtoodumbtofigureout531onmyown-staging.com/static
#     ports:
#       - 80:80
#     depends_on:
#       - web

volumes:
  static_volume: