version: '3.8'

services:
  web:
    build: .
    command: gunicorn lifting.wsgi:application --bind 0.0.0.0:${PORT}
    volumes:
    - static_volume:/home/sites/www.imtoodumbtofigureout531onmyown.com/static
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  static_volume:
  postgres_data: