version: '3.8'

services:
  web:
    build: .
    command: gunicorn lifting.wsgi:application --bind 0.0.0.0:8080
    volumes:
    - static_volume:/home/sites/www.imtoodumbtofigureout531onmyown.com/static
    ports:
      - 8080:8080
    env_file:
      - ./.env

volumes:
  static_volume: